// Generated by gencpp from file hybrid_astar/GlobalPath.msg
// DO NOT EDIT!


#ifndef HYBRID_ASTAR_MESSAGE_GLOBALPATH_H
#define HYBRID_ASTAR_MESSAGE_GLOBALPATH_H

#include <ros/service_traits.h>


#include <hybrid_astar/GlobalPathRequest.h>
#include <hybrid_astar/GlobalPathResponse.h>


namespace hybrid_astar
{

struct GlobalPath
{

typedef GlobalPathRequest Request;
typedef GlobalPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlobalPath
} // namespace hybrid_astar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hybrid_astar::GlobalPath > {
  static const char* value()
  {
    return "0002bc113c0259d71f6cf8cbc9430e18";
  }

  static const char* value(const ::hybrid_astar::GlobalPath&) { return value(); }
};

template<>
struct DataType< ::hybrid_astar::GlobalPath > {
  static const char* value()
  {
    return "hybrid_astar/GlobalPath";
  }

  static const char* value(const ::hybrid_astar::GlobalPath&) { return value(); }
};


// service_traits::MD5Sum< ::hybrid_astar::GlobalPathRequest> should match
// service_traits::MD5Sum< ::hybrid_astar::GlobalPath >
template<>
struct MD5Sum< ::hybrid_astar::GlobalPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hybrid_astar::GlobalPath >::value();
  }
  static const char* value(const ::hybrid_astar::GlobalPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hybrid_astar::GlobalPathRequest> should match
// service_traits::DataType< ::hybrid_astar::GlobalPath >
template<>
struct DataType< ::hybrid_astar::GlobalPathRequest>
{
  static const char* value()
  {
    return DataType< ::hybrid_astar::GlobalPath >::value();
  }
  static const char* value(const ::hybrid_astar::GlobalPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hybrid_astar::GlobalPathResponse> should match
// service_traits::MD5Sum< ::hybrid_astar::GlobalPath >
template<>
struct MD5Sum< ::hybrid_astar::GlobalPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hybrid_astar::GlobalPath >::value();
  }
  static const char* value(const ::hybrid_astar::GlobalPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hybrid_astar::GlobalPathResponse> should match
// service_traits::DataType< ::hybrid_astar::GlobalPath >
template<>
struct DataType< ::hybrid_astar::GlobalPathResponse>
{
  static const char* value()
  {
    return DataType< ::hybrid_astar::GlobalPath >::value();
  }
  static const char* value(const ::hybrid_astar::GlobalPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYBRID_ASTAR_MESSAGE_GLOBALPATH_H
