// Generated by gencpp from file hybrid_astar/MonteCarloSim.msg
// DO NOT EDIT!


#ifndef HYBRID_ASTAR_MESSAGE_MONTECARLOSIM_H
#define HYBRID_ASTAR_MESSAGE_MONTECARLOSIM_H

#include <ros/service_traits.h>


#include <hybrid_astar/MonteCarloSimRequest.h>
#include <hybrid_astar/MonteCarloSimResponse.h>


namespace hybrid_astar
{

struct MonteCarloSim
{

typedef MonteCarloSimRequest Request;
typedef MonteCarloSimResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MonteCarloSim
} // namespace hybrid_astar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hybrid_astar::MonteCarloSim > {
  static const char* value()
  {
    return "ef92dc717d72570cde39a1214c59cf11";
  }

  static const char* value(const ::hybrid_astar::MonteCarloSim&) { return value(); }
};

template<>
struct DataType< ::hybrid_astar::MonteCarloSim > {
  static const char* value()
  {
    return "hybrid_astar/MonteCarloSim";
  }

  static const char* value(const ::hybrid_astar::MonteCarloSim&) { return value(); }
};


// service_traits::MD5Sum< ::hybrid_astar::MonteCarloSimRequest> should match
// service_traits::MD5Sum< ::hybrid_astar::MonteCarloSim >
template<>
struct MD5Sum< ::hybrid_astar::MonteCarloSimRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hybrid_astar::MonteCarloSim >::value();
  }
  static const char* value(const ::hybrid_astar::MonteCarloSimRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hybrid_astar::MonteCarloSimRequest> should match
// service_traits::DataType< ::hybrid_astar::MonteCarloSim >
template<>
struct DataType< ::hybrid_astar::MonteCarloSimRequest>
{
  static const char* value()
  {
    return DataType< ::hybrid_astar::MonteCarloSim >::value();
  }
  static const char* value(const ::hybrid_astar::MonteCarloSimRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hybrid_astar::MonteCarloSimResponse> should match
// service_traits::MD5Sum< ::hybrid_astar::MonteCarloSim >
template<>
struct MD5Sum< ::hybrid_astar::MonteCarloSimResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hybrid_astar::MonteCarloSim >::value();
  }
  static const char* value(const ::hybrid_astar::MonteCarloSimResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hybrid_astar::MonteCarloSimResponse> should match
// service_traits::DataType< ::hybrid_astar::MonteCarloSim >
template<>
struct DataType< ::hybrid_astar::MonteCarloSimResponse>
{
  static const char* value()
  {
    return DataType< ::hybrid_astar::MonteCarloSim >::value();
  }
  static const char* value(const ::hybrid_astar::MonteCarloSimResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HYBRID_ASTAR_MESSAGE_MONTECARLOSIM_H
