// Generated by gencpp from file hybrid_astar/PathTracking.msg
// DO NOT EDIT!


#ifndef HYBRID_ASTAR_MESSAGE_PATHTRACKING_H
#define HYBRID_ASTAR_MESSAGE_PATHTRACKING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace hybrid_astar
{
template <class ContainerAllocator>
struct PathTracking_
{
  typedef PathTracking_<ContainerAllocator> Type;

  PathTracking_()
    : path()
    , direction()  {
    }
  PathTracking_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::hybrid_astar::PathTracking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_astar::PathTracking_<ContainerAllocator> const> ConstPtr;

}; // struct PathTracking_

typedef ::hybrid_astar::PathTracking_<std::allocator<void> > PathTracking;

typedef boost::shared_ptr< ::hybrid_astar::PathTracking > PathTrackingPtr;
typedef boost::shared_ptr< ::hybrid_astar::PathTracking const> PathTrackingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_astar::PathTracking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_astar::PathTracking_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hybrid_astar::PathTracking_<ContainerAllocator1> & lhs, const ::hybrid_astar::PathTracking_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hybrid_astar::PathTracking_<ContainerAllocator1> & lhs, const ::hybrid_astar::PathTracking_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hybrid_astar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_astar::PathTracking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_astar::PathTracking_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_astar::PathTracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_astar::PathTracking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_astar::PathTracking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_astar::PathTracking_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_astar::PathTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "828ba78ead1f8c45eb08d3a94a1d45c3";
  }

  static const char* value(const ::hybrid_astar::PathTracking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x828ba78ead1f8c45ULL;
  static const uint64_t static_value2 = 0xeb08d3a94a1d45c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_astar::PathTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_astar/PathTracking";
  }

  static const char* value(const ::hybrid_astar::PathTracking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_astar::PathTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path path\n"
"int8[] direction\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::hybrid_astar::PathTracking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_astar::PathTracking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathTracking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_astar::PathTracking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_astar::PathTracking_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "direction[]" << std::endl;
    for (size_t i = 0; i < v.direction.size(); ++i)
    {
      s << indent << "  direction[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.direction[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_ASTAR_MESSAGE_PATHTRACKING_H
