# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hybrid_astar/TestSummary.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TestSummary(genpy.Message):
  _md5sum = "bfac551d5488bc9c563aaa33200405e9"
  _type = "hybrid_astar/TestSummary"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 successful_tests
uint64 unsuccessful_tests
uint64 iteration_limits
uint64 total_tests"""
  __slots__ = ['successful_tests','unsuccessful_tests','iteration_limits','total_tests']
  _slot_types = ['uint64','uint64','uint64','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       successful_tests,unsuccessful_tests,iteration_limits,total_tests

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TestSummary, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.successful_tests is None:
        self.successful_tests = 0
      if self.unsuccessful_tests is None:
        self.unsuccessful_tests = 0
      if self.iteration_limits is None:
        self.iteration_limits = 0
      if self.total_tests is None:
        self.total_tests = 0
    else:
      self.successful_tests = 0
      self.unsuccessful_tests = 0
      self.iteration_limits = 0
      self.total_tests = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4Q().pack(_x.successful_tests, _x.unsuccessful_tests, _x.iteration_limits, _x.total_tests))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.successful_tests, _x.unsuccessful_tests, _x.iteration_limits, _x.total_tests,) = _get_struct_4Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4Q().pack(_x.successful_tests, _x.unsuccessful_tests, _x.iteration_limits, _x.total_tests))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.successful_tests, _x.unsuccessful_tests, _x.iteration_limits, _x.total_tests,) = _get_struct_4Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4Q = None
def _get_struct_4Q():
    global _struct_4Q
    if _struct_4Q is None:
        _struct_4Q = struct.Struct("<4Q")
    return _struct_4Q
